# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbfeb95ce74a7c7bc0ebee8c2dcf80990fc69a4ed8a3ea112da6f4716738c291bcb1e93787578207f3df664d7047f852d523a90746762754580984bc89f47545

test:
  secret_key_base: 1f7fcaef41acd84a6afa832606714f921b87d1ef49cff061d503f147009bc3e46ca10e67b74a2728ba24860ac023702628bbeb19e607578a21c2a021c0c82089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
